### ISSUE TITLE
Package 'petitboot' defined a second time

### ISSUE THREAD

**Issue by brichard19** [glevand/petitboot--buildroot#3]
Hi there,

I am trying to build petitboot for the PS3 but running into an error when running `make`:

```
~/git/petitboot--buildroot$ make ps3_petitboot_defconfig
#
# configuration written to /home/ben/git/petitboot--buildroot/.config
#
~/git/petitboot--buildroot$ make
/home/ben/git/op-build/openpower/package/petitboot/petitboot.mk:85: *** Package 'petitboot' defined a second time in '/home/ben/git/op-build/openpower/package/petitboot/'; previous definition was in 'package/petitboot/'.  Stop.
make: *** [Makefile:84: _all] Error 2
```

Is there a way to work around this?

Thanks.

**Comment by bdragon28** [comment]
> Hi there,
> 
> I am trying to build petitboot for the PS3 but running into an error when running `make`:
> 
> ```
> ~/git/petitboot--buildroot$ make ps3_petitboot_defconfig
> #
> # configuration written to /home/ben/git/petitboot--buildroot/.config
> #
> ~/git/petitboot--buildroot$ make
> /home/ben/git/op-build/openpower/package/petitboot/petitboot.mk:85: *** Package 'petitboot' defined a second time in '/home/ben/git/op-build/openpower/package/petitboot/'; previous definition was in 'package/petitboot/'.  Stop.

^^^ It's picking up an unrelated op-build checkout, did you accidentally try and build from a shell that you had done an . ./op-build-env in earlier?

> make: *** [Makefile:84: _all] Error 2
> ```
> 
> Is there a way to work around this?
> 
> Thanks.

**Comment by brichard19** [comment]
I got it to build. My mistake!
